sudo: false

language: c

compiler: gcc

notifications:
  email: false

addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - build-essential

env:
  global:
    - LUAROCKS=2.4.1
    - OPENRESTY=1.11.2.1
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache

before_install:
  - source .ci/setup_env.sh

install:
  - luarocks make

script:
  - make lint
  - ./rbusted -o=gtest -v

cache:
  apt: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
